### ISSUE TITLE
No such file or directory: 'res/org22.jpg'

### ISSUE THREAD

**Issue by igorbarinov** [PetroWu/AutoPortraitMatting#15]
Hi, thank you for the repository.

I'm trying to run your example with no luck.
* Downloaded original data
* Ran `data_download.m` and `generate_data_file.m` and copied to the `data/` folder
* Downloaded `imagenet-vgg-verydeep-19.mat` to `Model_zoo`
when I run `python FCN_plus.py` under py27/py36 I've got the same error:

```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:777] Peer access not supported between device ordinals 0 and 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:777] Peer access not supported between device ordinals 1 and 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y N 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 1:   N Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Graphics Device, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
(1, 800, 600, 2)
Traceback (most recent call last):
  File "FCN_plus.py", line 296, in <module>
    pred()
  File "FCN_plus.py", line 275, in pred
    org0_im.save('res/org' + str(itr) + '.jpg')
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 1695, in save
    fp = builtins.open(filename, "w+b")
IOError: [Errno 2] No such file or directory: 'res/org22.jpg'
```

Please help me figure it out.

**Comment by igorbarinov** [comment]
I figured it out, there is no `res` folder by default and I should create one.
