### ISSUE TITLE
Error when running FCN.py

### ISSUE THREAD

**Issue by sunalbert** [PetroWu/AutoPortraitMatting#3]
Hi, @PetroWu ,thanks for your work. When running both FCN.py and FCN_plus.py , I get the same errror:
`Traceback (most recent call last):
  File "FCN_plus.py", line 296, in <module>
    tf.app.run()
  File "/home/hjp/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "FCN_plus.py", line 160, in main
    name="entropy")))
  File "/home/hjp/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 265, in sparse_softmax_cross_entropy_with_logits
    logits, labels, name=name)
  File "/home/hjp/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 962, in _sparse_softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/home/hjp/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/home/hjp/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2156, in create_op
    set_shapes_for_outputs(ret)
  File "/home/hjp/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1612, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/hjp/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 273, in _SparseSoftmaxCrossEntropyWithLogitsShape
    input_shape = logits_shape.with_rank(2)
  File "/home/hjp/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 625, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (?, ?, ?, 2) must have rank 2`
It seems that the error is caused by the code at line 160.Have you encounterd this error? How to hanlde it?

**Comment by PetroWu** [comment]
I did't encounter this problem. I used Python3.5 and Tensorflow r0.12, and i guess this may be the problem of wrong version?

**Comment by MalcolmSun** [comment]
@PetroWu , Thanks.  For tensorflow, there is a bit of churn these days. Some apis are deprecated in the new version. Can you tell me your exact verion(you can confirm with a `print tf.__version__)?`  r0.12 is somewhat vague. Maybe I should change to your version to run the code. Thanks in advance.

**Comment by PetroWu** [comment]
my tf is 0.12.0, you can install this version on python3.5 can try again
