### ISSUE TITLE
Error when predict in FCN_plus

### ISSUE THREAD

**Issue by abrahamyan-lusine** [PetroWu/AutoPortraitMatting#4]
After training I try to run pred(), but get error

> setting up vgg initialized conv layers ...
Traceback (most recent call last):
  File "FCN_plus.py", line 297, in <module>
    pred()
  File "FCN_plus.py", line 242, in pred
    sft = tf.nn.softmax(logits)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1396, in softmax
    result = _op_def_lib.apply_op("Softmax", logits=logits, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2312, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1704, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 45, in _ShapeFunction
    return [op.inputs[0].get_shape().with_rank(rank)]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 641, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (?, ?, ?, 2) must have rank 2

Do You have any guess what is the problem?

**Comment by PetroWu** [comment]
The tensor 'logits' must be in shape of (batch, img_width, img_height, class_num), where class_num should 2 in this situation.
